name: Test

on:
  push:
    branches: '**'
    pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11.0
          - os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      - run: swift --version   

      - name: build
        run: swift build -c release

      - name: Swish Tests
        run: swift test
      
      - name: "Build example: DockerDev"
        run: swift build --package-path Examples/DockerDev

      
      - name: "Build example: AppIconRender"
        run: swift build --package-path Examples/AppIconRender

      - run: brew install imagemagick
      - name: "Run example: AppIconRender"
        run: swift run --package-path Examples/AppIconRender AppIconRender all
      

      - name: "Build example: Example iOS App"
        run: swift build --package-path Examples/ExampleiOSApp

      - name: "JSON scripts"
        run: swift run swish -f Examples/SwishScriptsExample/Swish.json bootstrap

      - name: "JSON scripts"
        run: swift run swish -f Examples/SwishScriptsExample/Swish.json bootstrap-plain

      - name: "yaml scripts"
        run: swift run swish -f Examples/SwishScriptsExample/Swish.yaml bootstrap

      - name: "yaml scripts"
        run: swift run swish -f Examples/SwishScriptsExample/Swish.yaml bootstrap-plain
