name: Test

on:
  push:
    branches: '**'
    pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11.0
            BUILD_CMD: swift build -c release
          - os: macos-10.15
            BUILD_CMD: swift build -c release
          - os: ubuntu-20.04
            BUILD_CMD: swift build -c release -Xswiftc -static-executable 
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      - run: swift --version   

      - name: Test
        run: swift test  --enable-test-discovery
